### ISSUE TITLE
Ability to "reset" ignored prompts

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals-feature-requests#100]
**Is your feature request related to a problem? Please describe.**
Currently for various features in Metals, you'll get a prompt to do an action, and often one of the options is to "Don't show again". If that option is chosen, there is no way to get that prompt back again unless you delete the `.metals` directory. 

**Describe the solution you'd like**
It might be nice to have a `metals/resetPrompts` command or something similar that could either reset all the prompts that are currently ignored or one specifically that is passed in as a param.

**Describe alternatives you've considered**
Depending on the situation, there is ways around it. For example if you ignore the one to import you build, you can still manually trigger this. Another option is to just blow away the `.metals` directory.

**Additional context**
The context for this is here https://github.com/scalameta/metals/pull/1607#discussion_r408212294

**Search terms**:
prompts

**Comment by tgodzik** [comment]
Fixed in https://github.com/scalameta/metals/pull/1897
