### ISSUE TITLE
Run compile, run command from Emacs

### ISSUE THREAD

**Issue by davidmlw** [scalameta/metals-feature-requests#102]
**Is your feature request related to a problem? Please describe.**

When I use emacs to edit a scala workspace, I'd like to compile and run Apps or Tests from emacs directly.

**Describe the solution you'd like**

It is better to have a compile and run command from emacs. And the project and tests can be passed to emacs as argument.

**Describe alternatives you've considered**

Maybe meteals has already support this, but I didn't know.

**Additional context**

**Search terms**:

**Comment by tgodzik** [comment]
Thanks for reporting. Compiling is currently done automatically after saving a file, while it should actually be possible to run/test in emacs via https://github.com/emacs-lsp/lsp-mode and https://github.com/emacs-lsp/dap-mode 

This is currently not documented properly in Metals, but if you manage to get it working we could maybe update it on the website?

**Comment by ckipp01** [comment]
I'm going to go ahead and close this. This would be great to be implemented in emacs! I think a better place for the feature request would be the following repo https://github.com/emacs-lsp/lsp-metals since the implementation would have to be there.

**Comment by ypytomets** [comment]
I see a default way to run tests is to use lsp code lenses: https://github.com/emacs-lsp/lsp-metals/issues/75
But the default Emacs's lsp mode, `eglot`, [doesn't has code lenses support](https://github.com/joaotavora/eglot/pull/71) (not everyone like complicated `lsp-mode`).  Anyway, that would be weird to depend on UI feature for such a basic functionality.

Currently I run it like `M-x` `projectile-compile-project` `nice bloop test myAwesomeProject-test -o my.AwesomePackage.DesiredTest -- "exact test"`.

But that's definitely a shame to do that manually, there's should be an lsp code action or something like [test](https://scalameta.org/metals/docs/editors/vscode/#via-test-explorer) [explorer](https://scalameta.org/metals/docs/integrations/test-explorer/) or at least [runnables](https://github.com/microsoft/language-server-protocol/issues/944).

Example how it's done in [nvim](https://github.com/scalameta/nvim-metals/discussions/553).
