### ISSUE TITLE
Add option to highlight unused expressions

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals-feature-requests#106]
**Is your feature request related to a problem? Please describe.**
In a purely functional codebase, any expressions whose values are unused are redundant or miss a connection to other, used expressions. Ideally the editor would show these expressions (for users who explicitly enable such behavior) as unused so that the mistake or redundancy can be fixed quickly.

**Describe the solution you'd like**
Metals showing expressions that aren't part of the return value of a function/block as unused, or maybe highlighting them as a warning.

**Describe alternatives you've considered**
Writing a scalafix rule... but it'll have to be semantic, so maybe it's worth just putting it in Metals.

**Additional context**

It is possible to highlight unused pure expressions (that I assume are only literals or a selected subset of methods known by the Scala compiler to be pure):

![image](https://user-images.githubusercontent.com/894884/80287312-28731780-8731-11ea-9e1d-edb16e16f1d8.png)

but as soon as the pure expression is part of a method call, it's no longer seen as pure and no warning is emitted:

![image](https://user-images.githubusercontent.com/894884/80287324-3a54ba80-8731-11ea-8d82-bb418bea8565.png)

It would be really valuable in code that does pure IO (or Futures, which when not used as part of other futures may cause tricky race conditions):

Bad:
![image](https://user-images.githubusercontent.com/894884/80287357-6708d200-8731-11ea-8898-f38a61080373.png)

Good:
![image](https://user-images.githubusercontent.com/894884/80287363-738d2a80-8731-11ea-86bf-e01e22335cc0.png)

**Search terms**:
Unused, missing operator, fp, expression oriented programming

**Comment by olafurpg** [comment]
Thank you for reporting! It’s unlikely Metals will implement custom diagnostics since these kinds or warnings should also be available to the build and be enforceable in CI.

The best way to implement this feature is probably via a custom WartRemover rule. Metals already displays all diagnostics in the build. 

Alternatively, down the road Metals will likely add an integration to display Scalafix linter warnings but I don’t know when that will happen. I think this analysis is easier to implement with WartRemover, however.

**Comment by kubukoz** [comment]
Yeah, I understand. I'll keep this open for a while if you don't mind, but I'll investigate other options :)

**Comment by kubukoz** [comment]
Note for future generations: there was no progress here and the suggestion to use wartremover/scalafix should be sufficient. Personally I don't encounter this issue often, and any amount of testing should allow you to catch issues like this.
