### ISSUE TITLE
Allow for temporary disable of scan and compile

### ISSUE THREAD

**Issue by mihaisoloi** [scalameta/metals-feature-requests#111]
In the real world things get ugly. Some projects end up with files of 10.000+ lines of code that take minutes to compile.

Currently metals scans continuously for changes in the files, and tries to compile something that is clearly not compileable, thus wasting time and resources, i.e. in many cases Metals just crashes or becomes unresponsive trying to compile it.

I would like to have a way to disable the automatic scan and compile. Ideally it would allow me to specify that I will compile this file specifically by CLI, and don't try to compile it.

P.S. On VSCode even with autosave disabled metals still gets triggered even when the file is not saved.

**Search terms**:
autosave, disable, compile, source, scan

**Comment by tgodzik** [comment]
Thanks for reporting! Nothing should be compiled unless the file is saved, the only errors show are the ones from the parser in that case. If it does compile anything, then that could be a bug.

**Comment by olafurpg** [comment]
Thank you for reporting! It's unlikely that Metals will offer an option to disable compile on file save because a lot of its features (diagnostics, completions, find references) require the project to be compiled. 

> P.S. On VSCode even with autosave disabled metals still gets triggered even when the file is not saved.

This sounds like an issue with your setup. Do you by any change have a background tool that edits sources? Metals only triggers compile on "file save" in the editor and file change notifications from our file watcher.

**Comment by mihaisoloi** [comment]
Thank you for explaining, it does make sense and I completely understand.

I believe it was a problem with the fact that I had autosave on recently and hadn't restarted VSCode/or metals for that matter after disabling it. I now see that it's behaving correctly after a VSCode restart.

I don't have any background tool that is editing my sources at the same time as myself.

**Comment by olafurpg** [comment]
Sounds good. Closing this as a wontfix. I'm open to discuss ways to improve the editing experience working on very large files. Metals may be doing some things today that hurt the experience in this scenario and could be fixed.
