### ISSUE TITLE
Add advanced completion options for Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals-feature-requests#112]
**Is your feature request related to a problem? Please describe.**
Currently, only basic completions are implemented for Scala 3.

**Describe the solution you'd like**
We'd like to have Scala 3 support on par with the existing Scala 2 one.
That would include:
- ~~match/case completions~~ https://github.com/scalameta/metals-feature-requests/issues/175
- ~~interpolator completions~~ https://github.com/scalameta/metals-feature-requests/issues/176
- ~~filename completions~~ https://github.com/scalameta/metals-feature-requests/issues/177
- arg completions
  - [x] Basic support https://github.com/scalameta/metals/pull/2369
  - [x] ~~findPossibleDefaults~~ https://github.com/scalameta/metals-feature-requests/issues/178
  - [x] ~~fillAllFields~~ https://github.com/scalameta/metals-feature-requests/issues/178
- ~~new completions~~ https://github.com/scalameta/metals-feature-requests/issues/179
- ~~override completions~~ https://github.com/scalameta/metals-feature-requests/issues/180
- ~~scaladoc completions~~ https://github.com/scalameta/metals-feature-requests/issues/181
- ~~type completions~~ https://github.com/scalameta/metals-feature-requests/issues/182

Hopefully, this would mostly be porting code from the Scala 2 completions, but in case this becomes more complicated we might need to split it into multiple issues.

**Search terms**:
completions scala3

**Comment by tanishiking** [comment]
Though it's still a work in progress, I started working on arg completions for scala3 this holidays
FYI https://github.com/tanishiking/metals/commit/cf5809d675b8c269b691c2ae997fa47c0f290a19

**Comment by tgodzik** [comment]
Cool, we might also be working on filtering and sorting soon, but it should not conflict with your work too much.

**Comment by tgodzik** [comment]
I split the issue into several other and will close in favour of those.
