### ISSUE TITLE
Semantic highlighting in VS Code

### ISSUE THREAD

**Issue by vasilmkd** [scalameta/metals-feature-requests#118]
**Is your feature request related to a problem? Please describe.**
No, just a pure feature request.

**Describe the solution you'd like**
Semantic highlighting in VS Code as described here: https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Additional context**
Probably a VS Code specific feature/implementation.

**Search terms**:
Semantic, highlighting, VS Code.

**Comment by Arthurm1** [comment]
Can this be closed as a duplicate of scalameta/metals#4685?

**Comment by vasilmkd** [comment]
Sure!
