### ISSUE TITLE
Worksheets for Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals-feature-requests#121]
**Is your feature request related to a problem? Please describe.**
Currently it's impossible to use worksheets with Scala 3 and after some work is done with scalameta parser and then mdoc, we should be able to provide a proper support. 

**Describe the solution you'd like**
Worksheets working via mdoc

**Describe alternatives you've considered**
Use REPL

**Additional context**
This is part of ongoing work around the Scala 3 support.

**Search terms**:
worksheets scala3

**Comment by ckipp01** [comment]
Closed with https://github.com/scalameta/metals/pull/1979

**Comment by tgodzik** [comment]
Thanks! I totally forgot about this :fearful:
