### ISSUE TITLE
VSCode: Show version(s)

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals-feature-requests#132]
**Is your feature request related to a problem? Please describe.**
When submitting bug reports, I have to include the Metals version. 

However, it's hard to find. 

And the VSCode extension deceptively only shows the version of the extension itself:

![image](https://user-images.githubusercontent.com/74843/83353395-f5b3d480-a317-11ea-8295-0dd8afac6f98.png)

**Describe the solution you'd like**
It would be nice to have a panel that shows the current version of all components, Bloop, Metals, Metals extension (and anything else?).

**Describe alternatives you've considered**
Manually spend time hunting down the version in some obscure place :smile:

**Comment by tgodzik** [comment]
Thanks for reporting! I think we could go even a step further. We could add an option to automatically generate bug reports:

- create .md file with version - scala version, bloop version, metals version
- add metals.log output (or last 100 lines etc) with anonimized workspace directory
- add some of the traces

This would be ready to paste into an issue. What do you think? This could be a fun project for someone I think.

**Comment by ckipp01** [comment]
Another low-hanging fruit option is that we could also make a simple command in the extension, like `metals-info` or something, that quickly displays the server version. This should be quite simple now after https://github.com/scalameta/metals/pull/1730 because we are now passing the server version to the client via `initializeParams`.

**Comment by logc** [comment]
Could you promote this issue to be not just for VSCode but also other editors? I have installed several metals releases for Emacs now, and whenever I open the [documentation](https://scalameta.org/metals/docs/editors/emacs.html) to see if there is a new version, I just do not remember if I have already installed it or not.

Ideally, I would want to have a simple `--version` flag on the installed CLI program that prints out the version string and exits:

```
$ metals-emacs --version
0.8.0
```

**Comment by gabro** [comment]
@logc yes, it makes sense that it's cross-editor. In the meantime, the Metals server version appears  in `.metals/metals.log` right after the server starts:

```
2020.08.18 15:53:27 INFO  started: Metals version 0.9.2 in workspace '/Users/gabro/dev/<redacted>` for client vscode.
```

**Comment by kpbochenek** [comment]
It is already implemented (somewhere between 0.9.1 and 0.9.2)

```
 λ metals-emacs -version
metals 0.9.2

# Note:
#   supported Scala versions: 0.24.0, 0.24.0-RC1, 0.25.0-RC2, 2.11.12, 2.12.10, 2.12.11, 2.12.12, 2.12.8, 2.12.9, 2.13.0, 2.13.1, 2.13.2, 2.13.3
```

**Comment by logc** [comment]
Ah, that is good, @kpbochenek , I will use that flag.

The log entry is not really a good solution, @gabro , because I as a user may want to check the version of the program without being in any particular project or creating a log. But thanks for pointing it out, it never occurred to me!

**Comment by gabro** [comment]
Ah sure, it was meant as a workaround :)

**Comment by kpodsiad** [comment]
Some time ago Metals doctor view got update and now it shows server version.
<img width="315" alt="Screenshot 2022-10-12 at 23 13 03" src="https://user-images.githubusercontent.com/37124721/195449072-4867fc36-4230-48e1-ba65-0c0b8473c0a8.png">

Is this enough to close this one @tgodzik?

**Comment by tgodzik** [comment]
I think that's enough. I don't think we need to do anything more than that.
