### ISSUE TITLE
Add a run this worksheet button on top

### ISSUE THREAD

**Issue by abhishekvaid** [scalameta/metals-feature-requests#135]
Scala `worksheet.sc` support is broken. My file often fails to execute which forces me to restart ide, server or simply close and reopen the file. 

If there could be a button on top (Dotty scalaIDE types) which reads "run this worksheet" it'll be super helpful.

**Comment by tgodzik** [comment]
Thanks for reporting! Could you elaborate on the problems you are having? In Metals saving the file is the equivalent of "run this worksheet" button, so if you are having issues with worksheets best to report those issues in the main tracker with some information about the context of the worksheet.

It's also important to note that worksheets do not work with Scala 3 currently, but they should work perfectly well for the Scala 2 workspaces.

**Comment by ckipp01** [comment]
I think we can go ahead and just close this since indeed saving the file is the equivalent of having a "run this worksheet" button. As @tgodzik said, if there are any specific issues you're having, feel free to open a ticket in the main repo.
