### ISSUE TITLE
Use installed Scala compiler

### ISSUE THREAD

**Issue by rim99** [scalameta/metals-feature-requests#146]
When I first start VSCode with Metals extension installed. I can see it downloaded a scala-compiler-2.12.12.jar from Maven Central.

My question is: 

Why cannot we use the Scala compiler we already installed at `/usr/local/bin`?

**Comment by kpbochenek** [comment]
Hi,
in `bin` directory you have your system executable. You can run it from your shell.
`scala-compiler.jar` is jvm code that which you can use in your java-like applications.

When you interface with jar file you have possibility to query compiler for things like completions, folding, imports, etc. Things that are not exposed in your binary.

Don't worry you won't download scala-compiler everytime you open your project, those jars are cached, you can see in your filesystem:
`~/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/`

It might seem like those are 2 the same things but technically they are not and you cannot replace one with the other.
