### ISSUE TITLE
Auto stop bloop server started by metals

### ISSUE THREAD

**Issue by jahan01** [scalameta/metals-feature-requests#147]
**Is your feature request related to a problem? Please describe.**
Bloop doesn't stop when I switch to non-scala project in vscode. I checked in gitter, and was informed this as designed, hence filing a feature request, not bug. I would love to bloop server started by metals to stop once I close the editor or switch to non-scala projects. Running bloop daemon might be useful for some, but not for others (majority I believe). This daemon might occupy valuable resources in a low end machine. Also bloop server daemon started several days ago, is super slow/buggy and anyways ll have to restart.

**Describe the solution you'd like**
Some options I propose (all these could be optional, enabled via settings)
1. Auto kill bloop daemon, started by metals when workspace is switched or closed (or)
2. Auto terminate bloop after x hours of inactivity.

**Describe alternatives you've considered**
I now manually kill bloop process. When old daemon is not responding I would kill and restart.

**Comment by tgodzik** [comment]
Thanks for reporting! There is already an issue for that here: https://github.com/scalameta/metals-feature-requests/issues/147

I will close this one, but it will be linked to the other one.
