### ISSUE TITLE
Hide and Show Metals sidebar icon on demand

### ISSUE THREAD

**Issue by xinstein** [scalameta/metals-feature-requests#151]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
the sidebar icon should only appear when a metals project is detected in the workspace and hide otherwise.

**Describe alternatives you've considered**

**Additional context**

**Search terms**:

**Comment by tgodzik** [comment]
Thanks for reporting! Just to confirm, do you mean the view on the left in the Metals VS Code extension?

![image](https://user-images.githubusercontent.com/3807253/93447208-718b5a00-f8d2-11ea-93c3-0ca3b85cc77c.png)

This should be possible by making a change to the configuration:
```
    "views": {
      "metals-explorer": [
        {
          "id": "metalsPackages",
          "name": "Packages",
          "when": "metals:enabled"
        },
        {
          "id": "metalsBuild",
          "name": "Build commands",
          "when": "metals:enabled"
        },
        {
          "id": "metalsCompile",
          "name": "Ongoing compilations",
          "when": "metals:enabled"
        },
        {
          "id": "metalsHelp",
          "name": "Help and feedback",
          "when": "metals:enabled"
        }
      ]
    },
```

However, that will also remove the welcome view, which enables people to create a new project, so I am not sure we want to do it currently. Let's see if there is more people wanting the change.

As a workaround, you can enable/disable metals extnesion per workspace.

**Comment by xinstein** [comment]
Hi, Thank you for the quick reply,
Can you please be more specific where I should put these configurations?
I tried to put it at the root of settings.json, but the popup says `unknown Configuration Setting`, and it has no effect

**Comment by tgodzik** [comment]
> Hi, Thank you for the quick reply,
> Can you please be more specific where I should put these configurations?
> I tried to put it at the root of settings.json, but the popup says `unknown Configuration Setting`, and it has no effect

Sorry, I wasn't clear enough. We need to change the configuration in Metals itself, which I am not 100% sure we want to do.

The only workaround I see is disabling Metals manually in workspaces it's not needed.

**Comment by xinstein** [comment]
Thank you, that sort of works, I'm ok if you think we should close

**Comment by tgodzik** [comment]
It's fine to leave it open and let people vote on it if they find the current behavior problematic. That's what this repo is for. Thanks for opening the issue! It's always useful to start the discussion about anything that doesn't look right. Otherwise, we will never know what people think :sweat_smile:

**Comment by tgodzik** [comment]
There doesn't seem to be much activity here, so closing!
