### ISSUE TITLE
Automatic case split (generate pattern matching boilerplate)

### ISSUE THREAD

**Issue by Kazark** [scalameta/metals-feature-requests#157]
# Problem

Pattern matching is the bread and butter of functional programming; functional programming is a major usecase of Scala. Don't know how to proceed? Pattern match. It's the secret recipe for getting unstuck. And when it comes to algebraic data types, generating basic pattern matching code is a matter of writing boilerplate.

Writing your own pattern matches, particularly if you have a large number of cases, can be laborious work. You may not remember all the details off the top of your head; in fact, unless you are working on something small and simple like `Either`, you probably don't. So you have to navigate back and forth, building it out.

# Potential Solution

One of the nicest things about working in Idris and Agda has nothing at all to do with dependent types. It is that they have built in functionality to do a case split: that is, for the compiler to generate pattern matching boilerplate for you. Here is an example in Agda. I trigger the pattern matching functionality in Spacemacs by placing my cursor in the typed hole (`{ }0`) and press `, c`. I am prompted for what variable I want to match on:

![Agda posed for pattern match](https://user-images.githubusercontent.com/3661051/96174526-6f2f1680-0ef7-11eb-955b-32fc0426b1ed.png)

Agda allows me to enter multiple variables at once, and then will generate a pattern match on all of them (you can thing of it as a sort of Cartesian product of all the possible pattern matches of each variable). The result is something like this:

![Agda generated pattern match](https://user-images.githubusercontent.com/3661051/96174609-8b32b800-0ef7-11eb-843f-20cbbe511120.png)

All those curly braces (`{ }N`) are typed holes; from a Scala perspective, we would probably just use `???`.

This implementation makes sense for Agda; the precise details of it would make a little less sense for Scala, since Scala doesn't have the same kind of pattern matching in equational definition of functions, or currying. However, the basic idea is the same: I have an algebraic data type; please generate pattern matching boilerplate for me. For example, in Scala if I had:

```scala
sealed trait MetasyntacticVariable
final case object Foo extends MetasyntacticVariable
final case object Bar extends MetasyntacticVariable
final case object Baz extends MetasyntacticVariable
final case object Qux extends MetasyntacticVariable
final case object Other(value: Symbol) extends MetasyntacticVariable

def foo(x : MetasyntacticVariable): Unit =
    ???
```

I would like some way to ask: "Please generate a pattern match on `x`", e.g. please generate this:

```scala
  x match {
    case Foo => ???
    case Bar => ???
    case Baz => ???
    case Qux => ???
    case Other(value) => ???
  }
```

Another interesting scenario that should be considered is if you wrote the original code this way:

```scala
def foo : MetasyntacticVariable => Unit =
    ???
```

It may be nice in this case as well to be able to ask for a pattern match to be generated of the form:

```scala
  {
    case Foo => ???
    case Bar => ???
    case Baz => ???
    case Qux => ???
    case Other(value) => ???
  }
```

Idris' approach might be one step closer to what would be useful in Scala. Here is an example. When I have the following code:

![Idris poised for pattern match](https://user-images.githubusercontent.com/3661051/96176630-9c30f880-0efa-11eb-9791-e8b4baf073d0.png)

where the `?demo_rhs` is a typed hole. With my cursor on `x`, when I press `, c` in Spacemacs, Idris generates the following:

![Idris generated pattern match](https://user-images.githubusercontent.com/3661051/96176934-0f3a6f00-0efb-11eb-8314-c591a6c0a444.png)

Again, all the `?demo_rhs_N`s are typed holes, and we would probably just want `???` in Scala. The solution of putting your cursor on the variable in question and pressing something may map better to Scala and LSP, than the Agda approach.

# Search Terms
* Pattern matching
* Case split
* Algebraic data types

**Comment by laughedelic** [comment]
If I understood you right, I think it already works: `x match`<kbd>Tab</kbd> you will get two autocompletion suggestions: a generic match snippet and an _exhaustive_ match which will produce all cases for the subtypes.

**Comment by Kazark** [comment]
@laughedelic Hm, that would be excellent. Perhaps my searchfu and API discovery skills have simply failed me here. Or, perhaps my Emacs is not configured correctly. I will give it a shot and report back.

**Comment by Kazark** [comment]
Yep. That was all. Simple.

**Comment by Kazark** [comment]
So my question is: how can I discover things like this for myself in the future? Perhaps I have not understood the power of `Tab` in the context of Metals use. I dug through my LSP menu, and ran internet searches, but couldn't discover this behavior.

**Comment by laughedelic** [comment]
Here's how it looks in VSCode:

![2020-10-15 22 21 04](https://user-images.githubusercontent.com/766656/96181973-1a11f580-0f35-11eb-8766-e919891d2618.gif)

**Comment by laughedelic** [comment]
Also, just for the reference, it's mentioned on in the docs: https://scalameta.org/metals/docs/editors/overview.html#completions 

> **Exhaustive match**: generate an exhaustive pattern match for sealed types.

Perhaps it's a matter of different terminology (coming from Agda/Idris) mislead your search?

**Comment by Kazark** [comment]
@laughedelic thank you. I definitely didn't search for the right terms. Obviously I need to re-read the docs as well; I had probably seen this at some point and forgotten.

**Comment by kpbochenek** [comment]
I understand your issue with finding this feature, if your completion triggers automatically during typing `match` keyword it is easy to spot, but if in your editor it triggers in some specific situations(e.g. after dot, manually after pressing TAB) or after not typing for Xms, I doubt you will ever find this because you never try completion directly inside keyword `match`.
For me personally it would be very cool to create explicit section in documentation describing this feature.
Also there is already nice gif by @laughedelic that can be used there.

Maybe adding section here https://scalameta.org/metals/docs/editors/overview.html#completions after `#completions` something like `#exhaustive-match` and describing how it works and how to trigger it.

If you looked for something and docs didn't describe it clearly you can always contribute to help others learn about it easier.

Maybe someone will one day contribute something to docs you find useful :)

Maybe even addition of some keywords to help haskellers/agda/idris people find it would be also awesome.
