### ISSUE TITLE
Fallback to the docstring of overridden symbols if the referenced symbol has no documentation

### ISSUE THREAD

**Issue by gabro** [scalameta/metals-feature-requests#16]
**Is your feature request related to a problem? Please describe.**
- docstrings of overridden methods don't expand @defined macros when they're defined in a supertype (see #https://github.com/scalameta/metals/issues/648)
- methods without docstrings that override a method which has a docstring, show no docstrings in Metals 

**Describe the solution you'd like**
See https://github.com/scalameta/metals/issues/648#issuecomment-482161898

**Describe alternatives you've considered**
Nothing so far.

**Search terms**:
scaladoc, docstring, define, variables

**Comment by tgodzik** [comment]
We now have a way to search for a parent symbol, so this should be doable, however it needs semanticDB instead of just the compiler, so not sure if it exactly helps the issue here.

**Comment by olafurpg** [comment]
We are already using the presentation compiler for finding the symbol when fetching docstrings so I don't think it makes a big difference in this particular case.

**Comment by tgodzik** [comment]
This should already work after some recent changes and both in Scala 2 and 3.
