### ISSUE TITLE
VSCode "env" environment variable support in launch.json

### ISSUE THREAD

**Issue by arjaron** [scalameta/metals-feature-requests#162]
**Is your feature request related to a problem? Please describe.**
When I work with GCP, I require the environment variable GOOGLE_APPLICATION_CREDENTIALS to be set. If it isn't, I can't debug my code inside of VSCode debugging. VSCode's "launch.json" has support for setting "env": {"KEY":"VALUE"}, and even "envFile", but this requires specific support by the language's plugin: Metals. Currently I just get a warning saying "Property env is not allowed", which is their term for: The plugin (metals) hasn't implemented this, yet.

**Describe the solution you'd like**
Support "env" and "envFile" in VSCode's launch.json (is streamlined already).

**Describe alternatives you've considered**
None. This is a basic feature of VSCode that just must work, otherwise too much of the functionality breaks.

**Search terms**:
env var

**Comment by tgodzik** [comment]
Thanks for reporting! Both using env and envFile should work with the next release that we are working on. I will update the issue as soon as it's available.

**Comment by tgodzik** [comment]
This should now be available after the new release. Let me know if you have any problems!
