### ISSUE TITLE
Warn if java boxed type is passed to Option[primitve type]

### ISSUE THREAD

**Issue by robstoll** [scalameta/metals-feature-requests#167]
**Is your feature request related to a problem? Please describe.**
null is converted to a default value instead of throwing an exception in scala. Following an example with Integer
```
val i: java.lang.Integer = null
val o : Option[Int] = Option(i) // Some(0)
```
The conversion happens before passing it to Option.apply. Or in other words, passing a java boxed type to Option only rarely makes sense and should most likely be done in two steps for clarity, i.e.
```
val ji: java.lang.Integer = null
val i: Int = ji
val o : Option[Int] = Some(i)
```

**Describe the solution you'd like**
Metals should warn the user in such situations

**Describe alternatives you've considered**
Warn always when there is a conversion from a java boxed type to a primitive but this might be too much because of:
```
trait A{
  var i :Int = _
}
```

**Search terms**:
java boxed type, nullable, implicit conversion

**Comment by tgodzik** [comment]
Thanks for reporting! In a lot of such cases Metals depends on compiler to show such warnings. Then, users can enable such specific flags in their build tool. That can later be enforced on CI as well as show in the editor.

Not sure though if there is any flag that can help here. Alternatively, wartremover might be helpful here: https://www.wartremover.org/. It's a compiler plugin that will show the warnings after compilation.

**Comment by robstoll** [comment]
I am actually using wartremover, seems like they don't have this wart in their toolbox. If I get you, then you don't include linters in metals. Feel free to close this issue, I am going to propose it to wartremover

**Comment by tgodzik** [comment]
Yes, we currently don't include linters inside metals. Metals server itself does not compile the code, instead we rely on build servers such as sbt, mill or Bloop, so it might be hard to implement currently. I think that wartremover might be a better place for it and can be reused in a number of places.

Another thing would be code actions to automatically refactor the code. It should be possible to depend on the warnings from wartremover to automatically refactor the code, which would 100% be in the Metals scope.

I will close the issue for now as I don't imagine we would implement it in any near future. Please do link the wartremover issue! Thanks!

**Comment by tgodzik** [comment]
Found the issue, it's https://github.com/wartremover/wartremover/issues/491 Thanks again!
