### ISSUE TITLE
Refactor package when moving classes in different folders

### ISSUE THREAD

**Issue by il-bert** [scalameta/metals-feature-requests#171]
**Is your feature request related to a problem? Please describe.**

when I'm moving a class/object from one folder to another, the package is not refactored to be aligned

**Describe the solution you'd like**

package should be aligned to the new folder

**Describe alternatives you've considered**

**Additional context**

**Search terms**:
package folder class object file

**Comment by ckipp01** [comment]
Thanks for the request! Closing as a duplicate of https://github.com/scalameta/metals/issues/4664
