### ISSUE TITLE
Refactoring support

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-feature-requests#18]
Currently, Metals doesn't provide any refactoring support. For the upcoming v0.6, we have assigned a ticket to implement "rename symbol" (https://github.com/scalameta/metals/issues/679).

After renaming, it would be nice to add basic refactoring actions such as:

- add import for "not found: $NAME" compile errors
- insert inferred result type for public member
- convert to block expression
```scala
// before
List(1).map(x => x + 1)
// after
List(1).map { x => x + 1 }
```
- convert to multiline string, and vice versa
```scala
// before
"Hello\nWorld"
// after
"""Hello
   |World""".stripMargin
```

Those would be good starting points and down the road we could introduce more advanced refactorings:

- move class with option to select new project and package name
- extract method
- inline method

Some challenges:

- Scalafix integration (https://github.com/scalameta/metals-feature-requests/issues/7), it would be nice if we could move as much as possible into Scalafix so that people can enforce the same refactoring rules in CI. However, not all code actions like "convert to multiline string" make sense in a Scalafix context.
- testing, what is the best way to test non-Scalafix refactorings?
- extensibility, how do we organize code actions so that it's easy to introduce new rules? In the future, we might have thousands of code actions! Some code actions only require basic inputs like tokens while other actions require fully type-checked source files.

**Search terms**: code actions, inspections

**Comment by torkelrogstad** [comment]
Another refactoring (which I believe is pretty simple) which I really miss from IntelliJ is the "Use named argument for current and subsequent arguments" action. Would be much appreciated if something like that could make its way into Metals!

**Comment by fkoehler** [comment]
I would like to see from intellij: "remove unnecessary parentheses" which highlights the extra parentheses and allows to remove them via a code action.

 I would be willing to help out here but I guess some more basic work needs to be done before I can "just" write a code action, no idea where to start currently.

**Comment by co-category** [comment]
I would like to see an equivalent to [Intellij's optimising of `import`s](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#optimize-imports)

**Comment by gabro** [comment]
Since we're slowly starting to tackle refactoring in Metals, this issue is not useful anymore in its current form.

I propose to keep the feature requests more focused and open separate ones for each refactoring.

So far we already support:
- renaming (which has special treatment in LSP)
- import missing symbol

I'm going to close this issue and re-open single ones so that we can analyze and prioritize them separately.

**Comment by co-category** [comment]
I just need solid refactoring support in Metals and then I can drop Intellij for good. With every update Intellij is getting slower and buggier and the user experience when trying to build Scala projects is terrible - it seems to have a mind of its own. Latest bug I experienced and which I have raised with them is this : https://youtrack.jetbrains.com/issue/SCL-16816

Damn bug froze my machine!

**Comment by gabro** [comment]
@co-category thanks for the encouragement! Feel free to open a feature request for specific refactors you consider essential to your workflow.

As an aside, please try to keep a positive tone in your messages. Despite Metals being a lightweight alternative to IntelliJ, we do so with a spirit of positive OSS collaboration and we do not tolerate harsh tones against it or other projects.

Thank you 🙏
