### ISSUE TITLE
Extract value

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals-feature-requests#186]
**Is your feature request related to a problem? Please describe.**

When I do:

```scala
val x = fun1(
  fun2(...),
  fun3(...)
)
```

Sometimes I'd like to create an intermediate expression for the value of `fun2(...)` or `fun3(...)`. I have to do it manually when using Metals.

**Describe the solution you'd like**

A code action around a highlighted expression could enable a user to specify a name for a new `val`, let's say the user entered `y`, then the action would change the code above to:

```scala
val y = fun2(...)

val x = fun1(
  y,
  fun3(...)
)
```

Unlike "extract method", *this could change semantics* in terms of side effects / impurity in the call to `f2` and its parameters, as well as make lazy evaluations eager (computation-wise), and users should probably be warned about that in a clear, yet non-obstructive way.

**Describe alternatives you've considered**

- Using IntelliJ for any kind of refactorings
- Living with the pain and doing this by hand

**Additional context**

A more sophisticated variant of this would be "extract method", but the solution to the issue here should be much simpler - e.g. there is no need to add imports for types of the method's arguments. This can be a next step :)

Also, this is sort of a dual to scalameta/metals#4724.

**Search terms**:

refactoring, extract method, extraction, refactor, symbol, inline

**Comment by TobiasRoland** [comment]
I wholeheartedly concur, this is my most used feature in IntelliJ and what's really keeping me from adopting VSCode/Metals - for those unfamilar, it looks something like this in IntelliJ when I place my cursor on a snippet I want to extract to a val or method and press the appropriate shortcut:


![image](https://user-images.githubusercontent.com/5878818/132331885-5f588a3c-2b94-4805-bb3f-729c8c6984f6.png)

**Comment by tgodzik** [comment]
Took a quick stab at it in https://github.com/scalameta/metals/pull/3297

Current limitations:
- it will choose the last function parameter under the cursor
- doesn't allow to choose the name (I have some ideas for that, but wasn't able to work on that yet)

**Comment by tgodzik** [comment]
The basic extract action has been merged. There are still some improvements we can do such as:

- extract from more places such as:

> - condition in while/if/doWhile
> - interpolate
> - return
> - throw
> - tuple
> - matched expression
> - new

- create action for each node in multi apply node such as `method1(method2( 1 + 2 * 23 ))` - we could extraxct `2 * 23`, `1 + 2 * 23` and `method2(1+ 2 * 23)`

**Comment by kubukoz** [comment]
I think I'll close it as the feature _exists_. We can create issues for any extra improvements later on, these issues would probably look less scary and more beginner-friendly than an entire feature :)
