### ISSUE TITLE
Run codegen actions when importing build / as a manual action

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals-feature-requests#187]
**Is your feature request related to a problem? Please describe.**

When I use the metals/bloop combo, some actions still need to be made with sbt - e.g. generating https://github.com/sbt/sbt-buildinfo files, or running Play codegen.

**Describe the solution you'd like**

Being able to run a command on demand, or having these actions run during build import.

Ths actions to run should probably be configurable on a per-project basis, so they'd likely have to go in a `.metals.conf` file or something of the like.

If they were to run during build import, I suppose it could be just additional sbt commands to run after `bloopInstall` or whatever gets triggered during the import. If it was "on demand", I think we would need to either keep an sbt instance running and call it with `sbt -client`, or start a fresh sbt instance every time, at which point I think we don't need Metals to participate (using something like https://marketplace.visualstudio.com/items?itemName=edonet.vscode-command-runner for VSCode would be enough).

**Describe alternatives you've considered**

Manually running the commands whenever a need arises, by opening sbt in another window and manually typing in the codegen tasks

**Search terms**:
codegen, code generation, generators, build import

**Comment by tgodzik** [comment]
Thanks for reporting! Code gen actions are run by `bloopInstall` or when sources are requested in sbt BSP. Did you find a situation where it doesn't?  I think that would be a bug on Metals side or maybe on a particular plugin's.

**Comment by kubukoz** [comment]
buildInfo is one that i remember having to run manually, and the same was with Play - maybe it's actually changed now, i didn't notice it being announced 😅 I'll see if it works.

**Comment by tgodzik** [comment]
> buildInfo is one that i remember having to run manually, and the same was with Play - maybe it's actually changed now, i didn't notice it being announced  I'll see if it works.

You might need to run them manually if you do `sbt clean` or maybe I am totally mistaken.

**Comment by kubukoz** [comment]
I think it works, closing then ;)
