### ISSUE TITLE
Configuration files search inside a dependency

### ISSUE THREAD

**Issue by mbesida** [scalameta/metals-feature-requests#196]
**Is your feature request related to a problem? Please describe.**

I didn't find a way how to lookup configuration files that reside inside a library which is on the classpath. It's possible only to find a class/type(Ctrl + T shortcut in VS code). VS code's functionlity that is represented by Ctrl+O shortcut only searches for files that are inside current project directory. For example, I want to see which keys are defined in `reference.conf` of some of the akka library to be able to override them in my project's `application.conf`. Another use case: there is a library which contains protobuf definitions under its `src/main/resource` and it would be great to view its content

**Describe the solution you'd like**

I would like to have an opportuniy to search for non java/scala files that reside inside a dependency of my project, at least for `.conf` or `.proto` files

**Comment by tgodzik** [comment]
Thanks for reporting! We are already looking through the source files for `java/scala` files. We could add a separate cache for any other files, though we might need to go through the normal jars instead of source jars here.

**Comment by mbesida** [comment]
@tgodzik I checked for akka-actor library, for example, and they pack reference.conf inside sources jar

**Comment by tgodzik** [comment]
Cool, thanks for checking! That should make it a bit simpler.

**Comment by Z1kkurat** [comment]
Heavy 👍 on this one. When dealing with anything typesafe-config related (i.e. akka ecosystem) there are tens of `reference.conf` files on the classpath and it's very convenient to be able to search for a particular config setting through these files

**Comment by tgodzik** [comment]
Closing it as it was implemented by @Z1kkurat :tada:
