### ISSUE TITLE
Switch parenthesis to braces and vice versa

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals-feature-requests#200]
**Is your feature request related to a problem? Please describe.**
Often when writing Scala code we might need to change an `()` in `{}` and doing that manually is a bit annoying

**Describe the solution you'd like**
Parser can detect if we are at a function call and suggest a code action to use for it.

**Describe alternatives you've considered**
Doing it manually or using separate extension such as   https://marketplace.visualstudio.com/items?itemName=pustelto.bracketeer 

**Additional context**
This was discussed on gitter as a potential improvement.

**Search terms**:
braces parens parenthesis code action

**Comment by kpodsiad** [comment]
Can be closed because it was implemented in https://github.com/scalameta/metals/pull/3061
