### ISSUE TITLE
Update metals-vscode vscode-languageclient dependency to 7.0.0 

### ISSUE THREAD

**Issue by Giggiux** [scalameta/metals-feature-requests#202]
**Is your feature request related to a problem? Please describe.**

In order to use `codeAction/resolve`'s feature implemented in [LSP 3.1.6](https://github.com/microsoft/vscode-languageserver-node#3160-protocol-600-json-rpc-700-client-and-700-server), the `vscode-languageclient` dependency of the [scalameta/metals-vscode](https://github.com/scalameta/metals-vscode) extension needs to be updated to version >7.0.0.

**Describe the solution you'd like**

Update the dependency and publish the new package. 

**Describe alternatives you've considered**

[--]

**Additional context**

We would like to use the `codeAction/resolve` LSP feature to separate CodeAction creation and their Resolution when complex computation is needed.
At the moment that's done using Commands, but since there is now a new way in the LSP would be nice to support it. 

**Search terms**:

codeAction/resolve Code action resolve dependencies

**Comment by ckipp01** [comment]
Thanks for creating this! Related, before this can actually be done this will also need to be tackled. https://github.com/scalameta/metals-languageclient/pull/223

**Comment by Giggiux** [comment]
Hey @ckipp01 is the issue with scalameta/metals-languageclient#223 just related to compilation errors, or is there more to check?
Because I could do a pull request there to fix the errors that were given from the compiler.
They were related to, essentially, what I think is `void`s being removed from the API.
An example is `NotificationType0<R0>` become `NotificationType0`

**Comment by ckipp01** [comment]
> Hey @ckipp01 is the issue with [scalameta/metals-languageclient#223](https://github.com/scalameta/metals-languageclient/pull/223) just related to compilation errors, or is there more to check?
> Because I could do a pull request there to fix the errors that were given from the compiler.
> They were related to, essentially, what I think is `void`s being removed from the API.
> An example is `NotificationType0<R0>` become `NotificationType0`

Yea I haven't actually looked closely at it, but ideally just getting everything to compile and pass tests should be enough. Then there will need to be some small changes probably in the VS Code extension and coc-metals (the two that use the library) to ensure everything keeps on rolling.
