### ISSUE TITLE
Add the configuration option to enable/disable Hover (type at point)

### ISSUE THREAD

**Issue by tribbloid** [scalameta/metals-feature-requests#209]
**Is your feature request related to a problem? Please describe.**

Yes: https://stackoverflow.com/questions/67662217/in-visual-studio-code-why-the-option-editor-parameterhints-enable-has-no-effe

**Describe the solution you'd like**

Add a config option to enable/disable hover (type info) on mouse cursor

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Search terms**:

disable type info on hover

**Comment by gabro** [comment]
@tribbloid thanks for reporting! I think you can achieve what you want by turning off `editor.hover.enabled` in VSCode. I've added a more comprehensive response here https://stackoverflow.com/a/67952213/846273

Let me know if that helps

**Comment by gabro** [comment]
In general, I don't think Metals needs an option to turn this off. You probably always want to have the information provided by `hover` available, you just want to avoid displaying that when hovering with the mouse, so it's a client-side configuration rather than a server one.

Fortunately VSCode allows for configuring this kind of behavior out of the box.

**Comment by tribbloid** [comment]
@gabro agreed, but the compilation and inspection information serves very different purposes. If they are all aggregated into the same interface, they could cause some readability issues

**Comment by gabro** [comment]
@tribbloid I think this is something to potentially bring up with the VSCode team.
There's little Metals can do in terms of customizing the UI of a specific editor, so I'll close this for now, but if you have additional details that can help narrowing down a more actionable feature request feel free to share them!

**Comment by tribbloid** [comment]
OK let me try.
