### ISSUE TITLE
Show Implicit Arguments and Show Implicit Conversions And Classes for Scala 3

### ISSUE THREAD

**Issue by adampauls** [scalameta/metals-feature-requests#217]
These features already exists for Scala 2. It [seems](https://gitter.im/scalameta/metals?at=60f5a80f17929c14e696eab3) that they do not yet work for Scala 3. I did not see an issue anywhere else and am also not sure whether this qualifies as a "feature request" since it's arguably a bug that the settings exist but do nothing for Scala 3, but I thought I'd be conservative. Thanks for the great software!

**Comment by tgodzik** [comment]
Thanks for reporting, we are still working on having it supported, but it requires some bigger changes in the compiler. First step is https://github.com/lampepfl/dotty/pull/12885 which will provide information about types, we also plan to work on writing the implicits/using data to semanticdb, which is used in Metals. That will be the next step.

We'll keep you posted on this issue!

**Comment by tanishiking** [comment]
As to the implicit arguments and conversions for Scala3, I just opened an issue to dotty https://github.com/lampepfl/dotty/issues/13135 :)

**Comment by adampauls** [comment]
Fantastic! Very excited about Metals.

**Comment by tanishiking** [comment]
Closing as show implicit arguments and show implicit conversions and classes for Scala3 is working!
We'll keep track the issue https://github.com/scalameta/metals-feature-requests/issues/217#issuecomment-939379585 in https://github.com/scalameta/scalameta/issues/2458
