### ISSUE TITLE
Show Implicit Arguments and Show Implicit Conversions And Classes keybinding and/or hover

### ISSUE THREAD

**Issue by adampauls** [scalameta/metals-feature-requests#218]
Show Implicit Arguments and Show Implicit Conversions And Classes are very useful settings. However, my development style, which I assume is common, is that I do most development with these settings turned off, but when I want to understand what code is doing, I reveal implicits. In IntelliJ, there implicits are shown on a per-editor basis. I don't personally think it's important how exactly it's configured, but it would be great if there were a single action that revealed implicits instead of having to click through to the global settings. It could be implemented like it is in IntelliJ, or there could just be a key binding for changing that setting. It could also be shown in a hover, though I prefer implementing it as decoration because then it is possible to navigate to the implicit definitions for implicit conversions.

**Comment by tgodzik** [comment]
Thanks for reporting this is already possible via `Metals: Toggle...` commands, which can be easily bound to a keyboard shortcut or invoked from a command palette in VS Code, if you are using another editor it should also be possible, but best to ask on gitter or discord.

**Comment by tgodzik** [comment]
We also provide that information on hover, but for editors that do not support decorations. We could do an alternative mode if needed, but I would rather keep to a minimum number of settings if possible.

**Comment by adampauls** [comment]
Perfect, didn't know about that. Thanks!
