### ISSUE TITLE
PLEASE clean up your project directories

### ISSUE THREAD

**Issue by zlabz** [scalameta/metals-feature-requests#220]
**Is your feature request related to a problem? Please describe.**

You create .bloop .bsp .metals and project directories REALLY? you should only put one directly in my project folder
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Search terms**:

**Comment by ckipp01** [comment]
@zlabz I recommend you reconsider the way you create issues. By creating in the manner you have, you're likely to not get any constructive response.

By reading your statement, it's clear you don't understand what those directories or being used for or why they are being created where they are, which is totally fine. However then a better way to phrase your question would be, "I'm unfamiliar with what the various directories are that are created when using Metals. Could you explain what each is for in order for me to better understand why all three are being created?". You're much more likely to get a constructive response.
