### ISSUE TITLE
Code action to add import for extension method in Scala 3

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals-feature-requests#228]
### Is your feature request related to a problem? Please describe.

When working in Scala 3 you will at times get diagnostics that mention that an import may fix the problem. For example I just tried using `"someString".toTermName` and Scala 3 returned this as a diagnostic

```
Diagnostics:
1. value toTermName is not a member of String, but could be made available as an extension method.
   
   The following import might fix the problem:
   
     import dotty.tools.dotc.core.Decorators.toTermName
```

### Describe the solution you'd like

In this situation I think it'd be perfect to also have a code action that can be triggered on `toTermName` which will offer to add the import in the same way we treat a `Not Found:` diagnostic. In this case, the code action would import `dotty.tools.dotc.core.Decorators.toTermName`

### Describe alternatives you've considered

Manually adding it.

### Search terms

Scala 3 extension code action import

**Comment by gabro** [comment]
I think this is exists already in terms of #105 and #141. How do I know? Because I've duplicated it too in the past (see #192).

Also worth mentioning my half-assed attempt at implementing it https://github.com/scalameta/metals/pull/2536

**Comment by ckipp01** [comment]
👀 I maybe didn't search before creating this like I should have 😆

> Also worth mentioning my half-assed attempt at implementing it scalameta/metals#2536

I totally forgot about this!

Closing this as a duplicate.
