### ISSUE TITLE
Make use of vs code testing-related API

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals-feature-requests#232]
### Is your feature request related to a problem? Please describe.

VS Code 1.59 has shipped with [test-related API](https://code.visualstudio.com/updates/v1_59#_testing-apis) which allows discovering tests, running them, and viewing error messages from UI and not console/code lenses.
![image](https://user-images.githubusercontent.com/37124721/132088136-0160fe9b-788a-44dc-8308-56b195573675.png)
(Picture from attached link)

### Describe the solution you'd like

I'd love to have such a beginner and user friendly way to run & manage tests. To start, basic support of a few most popular frameworks would be great.
An example of new API usage is among others [Java test runner](https://github.com/Microsoft/vscode-java-test)

### Describe alternatives you've considered

I think, there is no alternative way to achieve the proposed goal.

### Search terms

test lsp improvement

**Comment by kpodsiad** [comment]
Yes, but there's still room for improvement.

**Comment by tgodzik** [comment]
I will close it since I don't expect people to vote here if it's already implemented. We should raise separate tickets for possible improvements.
