### ISSUE TITLE
Auto-detect Scala 3

### ISSUE THREAD

**Issue by odersky** [scalameta/metals-feature-requests#241]
### Is your feature request related to a problem? Please describe.

We hear a lot of initial bad experiences from users since scalameta is parsing according to Scala-2 rules whereas the project is Scala 3. Yes, there are ways to tell Metals what project it is, but the fact is that these
rules are super-fragile. In my opinion unless you set up a Scala 3 project _exactly_ as specified it will default to Scala 2. 

This is really bad, since Scala 3 should be the default by now for beginners, and it ruins the very first steps of experience with the language. 

### Describe the solution you'd like

I see two solutions:

 - One: make Scala 3 the default. Presumably Scala 2 legacy projects are already correctly set up, so there's less need to improvise.
 - Two: auto-detect that a source is Scala 3. For regular program files, this could be very easy: A program is definitely Scala 3 source if the first definition is a class or object that has a `:` instead of `{` as a body. It is also Scala 3 if the first definition is not a class or object, since toplevel definitions are allowed only in Scala 3. For worksheets and scripts this would have to be refined a bit.

### Describe alternatives you've considered

So, I really would prefer option (1), make Scala 3 the default. If that does not work, we need good auto-detection. 

### Additional contex

I believe the status quo is a huge barrier to adoption, so it's urgent to fix this.

### Search terms

Scala 3, scalameta, auto-detect

**Comment by ckipp01** [comment]
Thanks for the comment @odersky. This actually should already be the case in the past two releases. In the past it used to be the case that as soon as Metals would start up it would use the fallback version, which was Scala 2, and then a user would often see a message on `@main` that scalameta couldn't parse it if the user directly opened up a `Main.scala` for example with Scala 3 syntax. As of https://github.com/scalameta/metals/pull/3134/files the fallback is now Scala 3, so if a user opens a file, even before any buildtarget is detected, they using Scala 3 as a fallaback. If you look in the `.metals/metals.log` you _should_ see something like this:

```
2021.11.14 12:49:52 INFO  no build target: using presentation compiler with only scala-library: 3.1.0
```
Which shows it is indeed falling back to 3.1.0.

We mentioned this in the release notes here: https://scalameta.org/metals/blog/2021/10/26/tungsten#miscellaneous

Do you have an example where this isn't working as expected and it is for some reason falling back to Scala 2?

**Comment by odersky** [comment]
I got reports from students but they might still be on an older installation. Great to learn that this is already addressed! I am closing the issue then.
