### ISSUE TITLE
Allow Metals to send custom commands in metals-show-stacktrace

### ISSUE THREAD

**Issue by ayoub-benali** [scalameta/metals-feature-requests#242]
### Is your feature request related to a problem? Please describe.

As discussed on [discord](https://discord.com/channels/632642981228314653/718047292749381662/914611170411970690) Metals should not sends vscode specific commands in the argument of `metals-show-stacktrace`

### Describe the solution you'd like

`command:metals.goto-path-uri?["file:///FILE_PATH",10,true]` should be converted depending on the client setting. For example sublime expects a command in this format `subl:open_file {'file': 'FILE_PATH'}`.

This behavior should probably controlled by a new initialization setting `commandInHtmlFormat`: `undefined` | `vscode` | `sublime` and we could deprecate `isCommandInHtmlSupported`.

### Describe alternatives you've considered

`LSP-metals` currently works around this using a regex but this setup is fragile and will break at any API change form vscode.
See: https://github.com/scalameta/metals-sublime/pull/55 

### Additional contex

![Peek 2021-11-29 12-17](https://user-images.githubusercontent.com/1632384/143858615-f5bcfc3e-d763-48f8-9cc1-de0ac0f61cdd.gif)

### Search terms

show stracktrace, sublime text

**Comment by tgodzik** [comment]
@ayoub-benali I took a stab at it in https://github.com/scalameta/metals/compare/main...tgodzik:support-sublime-command-links?expand=1

The sublime format is wrong for sure, but I wondering about a couple of things:
- can we add any kind of parameters or does it need to be an object? 
- do the parameters need to be URL encoded
- could we have the same name for the commands to use - `open_file_encoded` is not known by Metals

If you could help me out with it it would be awesome!

**Comment by ayoub-benali** [comment]
@tgodzik the doc for command format is here: https://www.sublimetext.com/docs/minihtml.html#protocols

> can we add any kind of parameters or does it need to be an object?

Parameters can be passed as you can see bellow or this example https://github.com/scalameta/metals-sublime/blob/master/core/handle_execute_client.py#L48

```
Valid subl: URL formats include:

subl:command_name
subl:command_name {"arg_name": arg_value, …}
```

> do the parameters need to be URL encoded

No need for encoding

> could we have the same name for the commands to use - open_file_encoded is not known by Metals

Yes I can create commands in the LSP-metals package that match the ones in metals. Just give me the list. 
But sublime need the command names to use the under_scores format :/ 

If you need help just grant me push permission to your branch and I would be happy to contribute :)

**Comment by Arthurm1** [comment]
Bit off the wall but - could the stacktrace be saved in a file in the readonly area under a filename such as `mytrace.metals-stacktrace` and then have Metals declare LSP support for `metals-stacktrace` extension?  Then metals can analyse the stacktrace file and supply semantic info so that the stacktrace lines each handle `goto definition`.  Then there would be no need for webviews or special commands and stacktrace analysis would be the same across all clients.  Plus you could save and/or analyse multiple stacktraces.

**Comment by tgodzik** [comment]
We kind of do something similar for clients that do not support webview, but with code lenses. 

> then have Metals declare LSP support for metals-stacktrace extension

Each client would need to be aware of that, so this is a bit of an issue, but I think it's overall a good idea that we could experiment with.

The main issue at hand is however the definition links in hovers, which I don't see any other way around than via links.

**Comment by tgodzik** [comment]
> ```
> Valid subl: URL formats include:
> 
> subl:command_name
> subl:command_name {"arg_name": arg_value, …}
> ```

Can it also be an array maybe? Or we could workaround by doing `subl:command_name {"arg1": arg_value, …}`

> Yes I can create commands in the LSP-metals package that match the ones in metals. Just give me the list. But sublime need the command names to use the under_scores format :/

I think we could convert is somewhere (sublime or metals server).
But currently we only use:
- https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala#L277
- https://github.com/scalameta/metals/blob/main/metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala#L286

Which are jsut forwarded to the server (though we need to register them in VS Code unfortunately)
> If you need help just grant me push permission to your branch and I would be happy to contribute :)

I added you to the repo! It would be awesome if you could iron it out.
