### ISSUE TITLE
Conversion between flatMap and for-comprehension

### ISSUE THREAD

**Issue by ghostbuster91** [scalameta/metals-feature-requests#245]
### Is your feature request related to a problem? Please describe.

While working with effect types I find myself often in the need of rewriting `op1.flatMap(opt2(_))` to a for-comprehension and sometimes back (for example after a refactor). It would be great to have a quick action that would perform such conversion automatically.
Please note that it doesn't have to be specific to any particular effect type as neither for-comprehension is. It can work with any usage of methods named map/flatMap.

### Describe the solution you'd like

Given following code:
```
op1.flatMap(opt2(_))
```

I would like to have a quick action available that would convert it into:
```
for {
result1 <- op1
result2 <- op2(result1)
} yield result2
```

I think that it would be also nice if we could convert it back to the original version.

### Search terms

for-comprehension flatMap

**Comment by tgodzik** [comment]
Thanks for reporting! That looks like a pretty cool idea, though the hard part would be figuring out if `map` and `flatMap` adhere to the right structural type.

**Comment by kubukoz** [comment]
@tgodzik is there actually a structural type? I thought the rewrite was purely syntactical. This all seems doable without Semanticdb or even a compiling codebase :)

**Comment by tgodzik** [comment]
> @tgodzik is there actually a structural type? I thought the rewrite was purely syntactical. This all seems doable without Semanticdb or even a compiling codebase :)

That might be right! I haven't delved into that too much.
