### ISSUE TITLE
Import Statement Completion

### ISSUE THREAD

**Issue by tanishiking** [scalameta/metals-feature-requests#259]
### Is your feature request related to a problem? Please describe.

When we write an import statement by hand, the auto-completion works only for the symbols that we can access from the scope corresponding to the cursor.

Like this:
![scala-import-completion](https://user-images.githubusercontent.com/9353584/156513223-a3e3f30f-32bf-4fa7-bd6f-a0d3d4403831.gif)

This feature is pretty useful, but

- If I'm not sure what package the symbol I want to import belongs to (For example, if I don't know where I can import `Semver` from), the auto-completion doesn't help.
  - In this case, I usually google the documentation or grep the source code to check the package name.
- Even if I know the fully qualified name of the symbol, writing the package name one by one is not handy.
 

### Describe the solution you'd like

I want to propose the feature available in Typescript 4.3 or higher, "Import Statement Completion."

For example, when we are writing an import statement like this:

```typescript
import useS|

// Typescript offers a completion to

import { useState } from "react"
```

like this ↓

![import-completion](https://user-images.githubusercontent.com/9353584/156514279-85e635f7-c3d1-4df3-88bd-5a64f07b9b26.gif)

This is a big time saver when I write TypeScript, and I wish Metals support this feature.

### references
- [TypeScript: Documentation - TypeScript 4.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#import-statement-completions)
- [Import statement completions by andrewbranch · Pull Request #43149 · microsoft/TypeScript](https://github.com/microsoft/TypeScript/pull/43149)

---

It will be awesome if Metals offers an import statement completion for

(for example)
```scala
import deriveEnc|

//to 

import io.circe.generic.semiauto.deriveEncoder
```

```scala
import semia|

// to 

import io.circe.generic.semiauto
```

### Describe alternatives you've considered

Not sure  ¯\_(ツ)_/¯

### Search terms

completion import

**Comment by tgodzik** [comment]
That sounds like a great idea! And it shouldn't be too hard to handle, we would need to modify the auto imports and reuse the logic there.

**Comment by olafurpg** [comment]
Import statements already support completions but auto-import suggestions only include classes (not methods, fields or packages).

**Comment by tgodzik** [comment]
Ach, right I must have blanked. Totally forgot about it :sweat:

**Comment by tanishiking** [comment]
self-assigned :)

**Comment by tanishiking** [comment]
> Import statements already support completions but auto-import suggestions only include classes (not methods, fields or packages).

Ah, right it works for classes

**Comment by tanishiking** [comment]
Sorry, never mind, there's already a feature like this :)
