### ISSUE TITLE
Clean build

### ISSUE THREAD

**Issue by torkelrogstad** [scalameta/metals-feature-requests#26]
Bloop sometimes has problems with knowing which projects to recompile. See https://github.com/scalacenter/bloop/issues/892. This causes VSCode to be of little use, because Metals can't compile the project I'm working on. I'd therefore like to have a action in VSCode for cleaning the build, similar to "Import build", "Reconnect to the server", etc.

**Comment by jvican** [comment]
We don't expose clean actions via BSP. You can clean the project in your terminal with `bloop clean $YOUR_PROJECT`, adding `--propagate` if you want it to indeed clean it up.

**Comment by olafurpg** [comment]
Thank you for reporting! @jvican there is a `buildTarget/cleanCache` request in BSP https://github.com/scalacenter/bsp/blob/master/docs/bsp.md#clean-cache-request iirc, IntelliJ has an option to run a "clean build". It could make sense to have something similar in Metals 🤔 

A workaround for now is to run `bloop clean ...` from the command-line when Bloop is installed on the computer. I'm not aware of a workaround when using the embedded Bloop server.

**Comment by jvican** [comment]
D'uh, i forgot we added that in one of the latest releases, it’s currently not implemented in bloop.

**Comment by tgodzik** [comment]
This was already implemented in https://github.com/scalameta/metals/pull/1677
