### ISSUE TITLE
Add more information to doctor's view

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals-feature-requests#264]
### Is your feature request related to a problem? Please describe.

Every now and then I have some hardcoded version of the Metals server or JDK about which I forgot that causes problems.

### Describe the solution you'd like

The doctor's view should include information such as the Metals server version and selected JDK.

### Describe alternatives you've considered

Checking this manually in the settings tab.

### Search terms

doctor

**Comment by kpodsiad** [comment]
I wonder what will be the best way to pass necessary data from the client to the server. I was thinking about adding another field to the `ClientConfiguration` or passing it by system props.

cc: @ckipp01, @dos65

**Comment by ckipp01** [comment]
Well since it's not really something a user will manually configure at all, maybe `initializationOptions` would be a better fit? Since the client has full control over what it sends in there, so we could create an object `systemDetails` or something and pass in a few different things the client knows to the server, and then just read them in?

**Comment by kpodsiad** [comment]
I was thinking about `MetalsInitializationOptions` but I was looking at Metals' `ClientConfiguration` which aggregates more options and I wrote second one instead.

`systemDetails` sounds great!

**Comment by kpodsiad** [comment]
After a short discussion with @dos65 we concluded that we have (or can have) all necessary information in Metals (JDK and server version). However, I think it will be beneficial to extend this information with some context like where sth it's defined. For example, in vscode there are 3 possibilities:
```
0.11.3-SNAPSHOT - default version from extension
0.11.3-SNAPSHOT - set in user settings
0.11.3-SNAPSHOT - set in workspace settings
```
or even just `default` vs `overwritten` can be useful for user.

It could be modeled with the following interface
```typescript
interface Setting {
  value: string;
  explanation?: string;
}
```

@ckipp01 what does it looks like from nvim side, will such an interface be useful?

**Comment by ckipp01** [comment]
It's someone similiar with you could have the following versions set for the `serverVersion`:

- `latest.release` - this is used by default
- `latest.snapshot` - this dynamically grabs the latest snapshot and sets it
- `0.11.3-SNAPSHOT` - the user manually set this

The difference is though that we don't dynamically check these every time you start metals like you do in the other extensions. This value is only ever read when you trigger a `:MetalsUpdate` or `:MetalsInstall`. So I don't think the `explanation` part would be _that_ useful for nvim tbh.

**Comment by kpodsiad** [comment]
In the next release, Metals doctor will contain:
- [x] Metals server version
- [x] JDK which was used to run Metals

so I'm closing this as implemented.
