### ISSUE TITLE
Inlay Hint support for "show-inferred-type", "show-implicit-arguments", and "show-implicit-conversions"

### ISSUE THREAD

**Issue by tanishiking** [scalameta/metals-feature-requests#274]
### Is your feature request related to a problem? Please describe.

Now [LSP 3.17.0](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification) is "current" version, and LSP 3.17.0 supports [Inlay Hint](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint) feature.

Currently, Metals uses our original [DecorationProtocol](https://scalameta.org/metals/docs/integrations/decoration-protocol) to show inferred-type, implicit-args, and implicit-conversions.

However, it would be ideal for better maintainability to align with the LSP standard (Inlay Hint, instead of DecorationProtocol), so we don't need to maintain the client-side implementation of DecorationProtocol each editor.

### Describe the solution you'd like

- Support Inlay Hint version of `show-inferred-type`, `show-implicit-arguments`, and `show-implicit-conversions`.
- Users can choose which version (DecorationProtocol or Inlay Hint) to show that additional information.
- Deprecate the DecorationProtocol version in the future, and move to Inlay Hint ones.

### Describe alternatives you've considered

As those features are available for the main editors (VSCode, nvim, and emacs), we don't need to rush into Inlay Hint and stay with Decoration Protocol for a while.

### TypeScript and JavaScript
https://code.visualstudio.com/updates/v1_60#_inlay-hints-for-javascript-and-typescript

<img src="https://code.visualstudio.com/assets/updates/1_60/ts-inlay-parameters.png"/>

### Rust analyzer
https://rust-analyzer.github.io/manual.html#inlay-hints

<img src="https://user-images.githubusercontent.com/48062697/113020660-b5f98b80-917a-11eb-8d70-3be3fd558cdd.png" />

### Search terms

Inlay Hint, Decoration Protocol, show inferred type, show implicit arguments, show implicit conversions and classes

**Comment by tgodzik** [comment]
There is also [inlineValue](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlineValue), which I wonder if we could try and use for worksheets.

**Comment by tgodzik** [comment]
I added a working version here https://github.com/scalameta/metals/compare/main...tgodzik:metals:add-inlay-hints?expand=1

Still needs hover plus commands

**Comment by wjoel** [comment]
@tgodzik what's the status on this issue nowadays? I don't get inlay hints in Emacs when using Metals with eglot, or lsp-mode.

I might have a go at making this work, if it doesn't already (somehow), but I might need some pointers in what direction to start. Inlay hints don't work in IntelliJ with Scala 3, and I was really hoping to see them working with Metals in Emacs. ;)

**Comment by tgodzik** [comment]
There is a PR ready for that, but we need to finish it and then merge. Shouldn't be much more work.

**Comment by tgodzik** [comment]
This is now merged and available in snapshots
