### ISSUE TITLE
Trigger the expression type/symbol signature popup with a keyboard shortcut

### ISSUE THREAD

**Issue by mwz** [scalameta/metals-feature-requests#29]
**Is your feature request related to a problem? Please describe.**
For those who prefer to get as much done as possible with their keyboard, it would be nice to be able to bring up the type info popup with a keyboard shortcut, just like in IntelliJ (through the "Type info" action).

**Describe the solution you'd like**
Just like you can see the expression type popup when you hover your mouse over the code, you can also trigger it with a keyboard shortcut. (I'm not sure what the corresponding command would be in vscode, maybe `editor.action.peekTypeDefinition`?)

**Describe alternatives you've considered**
It could be the same popup that you get on hover or a simple one which just shows you the type of value definition or the expression under the caret. 

**Search terms**:
type info popup

If people are ok with this feature and it's relatively easy to implement I'd be happy to give it a go (if someone could point me to where to start 😄).

**Comment by olafurpg** [comment]
Thank you for reporting! What editor are you using? Metals does not have control over editor shortcuts, it only responds to requests sent by the editor so there it not nothing we can do to fix this issue on our side.

**Comment by mwz** [comment]
Hi @olafurpg, I was referring to VSCode in this particular example. Are you saying that it is not possible to implement this functionality at all or is it something that could be done in https://github.com/scalameta/metals-vscode instead and you closed this issue because it's irrelevant to this project?

**Comment by olafurpg** [comment]
In VS Code you can configure the "Hover" shortcut to trigger the type/symbol popup from the keyboard

<img width="1355" alt="Screenshot 2019-06-28 at 10 49 14" src="https://user-images.githubusercontent.com/1408093/60330300-71800100-9992-11e9-82a1-c89be5af5917.png">

**Comment by mwz** [comment]
That's awesome, thanks for the tip 👍
