### ISSUE TITLE
Offer exhaustive completions for `map` and other methods

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals-feature-requests#302]
### Is your feature request related to a problem? Please describe.

When mapping over `List[A]` where A is a sealed trait I sometimes want to use more concise syntax than pattern matching - I don't know what is the proper name of it but it looks like a partial function but exhaustiveness is checked at compile time.
Unfortunately, Metals doesn't offer exhaustive completions in this case.
```scala
//> using scala "2.13.8"

sealed trait A
final case class B(value: Int) extends A
case object C extends A

object Main extends App {
  val x: List[A] = ???

  x.map { ca@@}
}
```
<img width="246" alt="Screenshot 2022-09-14 at 10 21 39" src="https://user-images.githubusercontent.com/37124721/190101417-843b27eb-6c18-4164-9f33-2d82bfb696f5.png">

### Describe the solution you'd like

Metals offer exhaustive completions just like for the pattern matching

### Describe alternatives you've considered

1. Do placeholder pattern match
2. Use existing code action and convert placeholder to function
<img width="268" alt="Screenshot 2022-09-14 at 10 21 46" src="https://user-images.githubusercontent.com/37124721/190101451-0108a749-dfbb-482d-8a5f-a42d99fade0c.png">
<img width="456" alt="Screenshot 2022-09-14 at 10 21 55" src="https://user-images.githubusercontent.com/37124721/190101454-2bd7fe65-fb99-4652-ba61-4da0ee9b9c8a.png">

### Search terms

pattern match, completions

**Comment by kpodsiad** [comment]
@jkciesluk this looks like an interesting feature, doesn't it? ;)

**Comment by jkciesluk** [comment]
It looks like a great feature and should be quite easy to implement, so I will take a look at it

**Comment by jkciesluk** [comment]
Do you have an idea how should we suggest this completion (what could be a label)?

**Comment by kpodsiad** [comment]
maybe sth similar to the one used for exhaustive match?  `case (exhaustive) n cases`?

**Comment by jkciesluk** [comment]
And it works!

https://user-images.githubusercontent.com/72950514/190126897-7ad67f2a-1053-45b7-8c84-6f0b60f2e676.mov


For now the label is the same as for normal match completion, but we can change it later. I will create a PR after merging https://github.com/scalameta/metals/pull/4356

**Comment by dos65** [comment]
@jkciesluk Maybe in addition to `match (exhaustive)` also provide the same with `case (exhaustive)`? This would allow to discover this completion if a user just start typing cases manually

**Comment by jkciesluk** [comment]
@dos65 Good idea, done. There is just one issue, i.e. in this case we are collecting subclasses twice (since exhaustive match works a bit different than basic `case @@` completion). Would it cause issues with efficiency?

**Comment by dos65** [comment]
@jkciesluk I don't know - I'm not familiar with this part of codebase. Let's for for the PR and decide if it's an issue or not)

**Comment by tgodzik** [comment]
@jkciesluk I think this can be closed or what else do we need to do?

**Comment by jkciesluk** [comment]
@tgodzik I think we can close
