### ISSUE TITLE
Support for using `run` in Scala Native `@main` methods

### ISSUE THREAD

**Issue by spamegg1** [scalameta/metals-feature-requests#325]
### Is your feature request related to a problem? Please describe.

Currently the `run` and `debug` buttons do nothing for Scala Native, so it's a bit confusing / misleading. 

### Describe the solution you'd like

I'm guessing `debug` would be hard to implement, but maybe `run` is possible? 

### Describe alternatives you've considered

N/A

### Additional context

Inspired by the [discussion on Discord](https://discord.com/channels/632642981228314653/632841682211045396/1068877632747360297)

![native-main](https://user-images.githubusercontent.com/4255997/215269058-7f2aff11-d219-4b26-82d2-23f86ee52f13.png)

### Search terms

scala native scala3 main run debug

**Comment by tgodzik** [comment]
We discussed it briefly on Scala Native discord and the best solution would be to use the run capability of BSP

I tried it and I think this could work, the only issue is reporting the output:
https://github.com/tgodzik/metals/pull/new/run-native

**Comment by tgodzik** [comment]
Took a stab at it today and I have some nice results, though there is a bit of ducktape here.

![test-unused-1676153138274](https://user-images.githubusercontent.com/3807253/218283156-77345668-da2b-4056-b497-42e2fb06866c.gif)

**Comment by spamegg1** [comment]
:partying_face:

**Comment by spamegg1** [comment]
Not working in Native 0.5.0-RC1.

**Comment by tgodzik** [comment]
Looking into it here https://github.com/scalacenter/bloop/pull/2293
