### ISSUE TITLE
Ability to enable Metals for only a subset of projects

### ISSUE THREAD

**Issue by armanbilge** [scalameta/metals-feature-requests#332]
### Is your feature request related to a problem? Please describe.

Builds may contain many (sub-)projects. E.g. 10 modules x 3 scala versions x 3 platforms = 90 projects. Loading all of these into Metals is not the funnest day :) particularly if you are only working on a subset of them. In practice a single platform and single scala version is sufficient.

### Describe the solution you'd like

Bleep has an interesting feature where it allows you to select the specific subset of projects you are interested in.

https://bleep.build/docs/usage/selecting-projects/

### Describe alternatives you've considered

- https://github.com/typelevel/sbt-typelevel/pull/465

### Search terms

cross-building, platforms

**Comment by armanbilge** [comment]
Related to this feature request I think, but I'm not entirely sure.
- https://github.com/scalameta/metals-feature-requests/issues/13

**Comment by armanbilge** [comment]
Aha, this is a duplicate of https://github.com/scalameta/metals/issues/6782! Sorry I missed it in my initial search :)

**Comment by tgodzik** [comment]
No worries @armanbilge I wonder if you have anything more to add. What is the exact issue you are seeing, what happens within Metals that might be slowing things down? Do you have a project maybe where we could experiement? We can continue the conversation on the other issue. This looks like something more along the lines of a bug really.
