### ISSUE TITLE
Scope-based cursor location information

### ISSUE THREAD

**Issue by susuro** [scalameta/metals-feature-requests#342]
### Is your feature request related to a problem? Please describe.

When analyzing code in a large source file, it is often troublesome to tell the current position in the scope hierarchy - current class/object (inner class/inner object), current method (and nested method), etc. This is even harder with significant indentation.

### Describe the solution you'd like

I would like to have the nested scope hierarchy of the cursor position presented in the editor. For example, in the following case: 
```scala
object Outer:
  object Inner:
    def outer:
      def inner:
        new Trait:
          // I'm here
```
when the cursor is in the line with "I'm here", the information should be:
```
Outer$: Inner$: outer: inner: Trait
```
It can be presented as part of Metals status information (in Sublime Text this is the lower left corner of the editor).

### Describe alternatives you've considered

Scrolling up while keeping track of indentation ;)

### Additional context

IntelliJ has a similar feature (Navigate / File Structure). It doesn't present nested methods, only classes and objects. It is not presented constantly.

### Search terms

scope, position info

**Comment by tgodzik** [comment]
Thanks for reporting, wouldn't it be the same thing as documentSymbols request? Though, it depends on the editor to properly present that information. I has all the ranges and labels to use. In VS Code you can set "Follow cursor" option and it will show exactly where in the outline you are currently located

You can probably ask or raise a feature request in https://github.com/sublimelsp/LSP

**Comment by susuro** [comment]
Thank you for your feedback. I wasn't aware of such a feature in VS Code. This is precisely what I would like to have in Sublime.
I'll make a feature request in Sublime LSP - I see now that this has to be implemented on the editor side.
I'm closing this issue.

**Comment by tanishiking** [comment]
@susuro Maybe you like the following VSCode feature / extension ;) (and there might be a same kind of extension in sublime)

- https://github.com/amos402/vscode-scope-bar
- https://code.visualstudio.com/updates/v1_70#_editor-sticky-scroll

Both of them utilizes `DocumentSymbol` requests of LSP, so they should be implementable in any languages / editors in theory.
