### ISSUE TITLE
Display full command when debugging in VS Code

### ISSUE THREAD

**Issue by ioleo** [scalameta/metals-feature-requests#352]
### Is your feature request related to a problem? Please describe.

When I run debugging in VS Code, I can't see what command is exactly being run, so I cannot verify that the command is as I need it to be.

### Describe the solution you'd like

I would like to print the full command being run when debugging.

### Describe alternatives you've considered

No alternatives.

### Search terms

vscode debug command

**Comment by adpi2** [comment]
Thanks for the request. I'll open a PR to  print the full command to Metals log.
