### ISSUE TITLE
Allow setting default build server

### ISSUE THREAD

**Issue by fabianMendez** [scalameta/metals-feature-requests#358]
### Is your feature request related to a problem? Please describe.

In VSCode I currently have to import the project with Bloop and only after that I can switch the build server to use sbt.

### Describe the solution you'd like

Having a vscode configuration that allows me to set sbt as the default build server.

### Describe alternatives you've considered

Keep importing projects with Bloop first and then switching to sbt.

### Search terms

sbt build server

**Comment by tgodzik** [comment]
Thanks for reporting! It should be pretty simple to add a setting for that. If anyone wants to take a look, let me know.
