### ISSUE TITLE
View of implicits in scope

### ISSUE THREAD

**Issue by iusildra** [scalameta/metals-feature-requests#362]
### Is your feature request related to a problem? Please describe.

While implicits are awesome, they can sometimes be tricky and it can be hard to find the right instance of implicit used in a given scope

```scala
// File A
object implicits:
  def foo(x: Int)(using y: Int): Int = x + y

object test:
  implicits.foo(1) // (given_Int) <- where is it defined ?

// File B
given Int = 42
```

### Describe the solution you'd like

A view of the implicits in the current scope, to then display it somewhere in the IDE. For the example above, it could return

```
B.given_Int
```

(This could also help lower the difficulty for newcomers)

### Describe alternatives you've considered

None

### Search terms

implicit, given, context

**Comment by tgodzik** [comment]
Thanks for reporting! You should be able to go to definition via the link in hover over implicit parameter decoration (can be turned on in the settings)

![image](https://github.com/scalameta/metals-feature-requests/assets/3807253/bd2a1f8d-122d-41b5-9337-a3a80bfdc9c9)

We will be working on adding inlay hints instead, which should be much easier to use.

**Comment by tgodzik** [comment]
Inlay hints are now implemented so it should be much more seamless
