### ISSUE TITLE
Autocomplete for Type Alias

### ISSUE THREAD

**Issue by nguyenyou** [scalameta/metals-feature-requests#385]
### Is your feature request related to a problem? Please describe.

<img width="723" alt="Screenshot 2024-05-28 at 21 35 14" src="https://github.com/scalameta/metals-feature-requests/assets/38455472/59f88e3c-f14d-405d-b639-1d42207f6ca7">

cc @tgodzik 

### Describe the solution you'd like

We have autocomplete while typing out the value

### Describe alternatives you've considered

n/a

### Search terms

Autocomplete

**Comment by scarf005** [comment]
could this issue be closed since https://github.com/scalameta/metals-feature-requests/issues/385 landed?

**Comment by nguyenyou** [comment]
Closed as completed.
