### ISSUE TITLE
Support scala 3.6's new given syntax without `with`

### ISSUE THREAD

**Issue by dragove** [scalameta/metals-feature-requests#406]
### Is your feature request related to a problem? Please describe.

in scala 3.6.2 repl, following code can be interpreted
```scala
trait T[A]:
  def foo(x: A): Unit
given T[Int]:
  def foo(x: Int) = println()
// Run it in REPL result
scala> trait T[A]:
     |   def foo(x: A): Unit
     | given T[Int]:
     |   def foo(x: Int) = println()
     | 
// defined trait T
// defined object given_T_Int
```

but metals gives an error 
```
• `identifier` expected but `indent` found
```

### Describe the solution you'd like

make `given T[Int]:` work just like `given T[Int] with`

### Describe alternatives you've considered

-

### Search terms

given typeclass with

**Comment by SethTisue** [comment]
it's in the pipeline: https://github.com/scalameta/scalameta/pull/4068

**Comment by dragove** [comment]
Thanks, it works on `metals 1.4.2`.
