### ISSUE TITLE
Allow users to disable display of Release Notes

### ISSUE THREAD

**Issue by Dessix** [scalameta/metals-feature-requests#409]
### Is your feature request related to a problem? Please describe.

Unless I'm missing it, there doesn't seem to be a way to disable the display of Metals release notes upon updating.

### Describe the solution you'd like

An extension setting or even a checkbox in the release notes page to disable them would be nice.

### Describe alternatives you've considered

Uninstalling Metals is less preferable, and writing another extension to automate closing it sounds like a lot of effort. Simply closing the window, obviously, is out of the question.

### Search terms

Release notes, settings, preferences

**Comment by tgodzik** [comment]
Thanks for raising this! I remember other people also complaining, I created a PR for it, so next version will have a setting to ignore the notes

**Comment by Dessix** [comment]
Awesome, thank you ^^
