### ISSUE TITLE
Quick Fix: add import

### ISSUE THREAD

**Issue by Daenyth** [scalameta/metals-feature-requests#43]
**Is your feature request related to a problem? Please describe.**

When I write code, I don't want to manually manage my import list or spend time thinking about which package to import from. Currently, if I type a class or object name that isn't in scope, I have to manually add an import for that class, often using the "symbol search" to find it instead of autocompleting

**Describe the solution you'd like**

I'd like a Quick Fix action on `not found` compile errors that searches known types and objects in the classpath, and automatically adds an import for that.

When multiple items exist, I should have a dropdown selection to pick the preferred one

**Describe alternatives you've considered**

A complement to this feature which is potentially easier to implement first, but doesn't replace it, is to be able to autocomplete imports by class name, for example:

> import Monad<kbd>TAB</kbd>

expands to

> import cats.Monad

**Additional context**
Intellij supports this
![Screen Shot 2019-08-23 at 1 05 26 PM](https://user-images.githubusercontent.com/14644/63610164-bdbc7b80-c5a6-11e9-864d-d0f074d38348.png)

**Search terms**:
autocomplete
import
missing

**Comment by tgodzik** [comment]
We already support automatically adding imports when using completion, is it working for you?

Quick fix action would also be nice, but if auto imports are not working for you then it's a bug.

**Comment by Daenyth** [comment]
I'll check again

**Comment by gabro** [comment]
@Daenyth autocompletion of `import` should work the same in Metals. Here's an example:

![2019-08-26 18 09 18](https://user-images.githubusercontent.com/691940/63705081-ba3a2600-c82c-11e9-9833-60ef33ad15bb.gif)

Also, if you already using a type and you want to import it you can trigger autocompletion (ctrl+space) while on it. It would be more appropriate to also have a quick-fix, and I think it will in the future, but this is already quite close:

![2019-08-26 18 13 24](https://user-images.githubusercontent.com/691940/63705367-3d5b7c00-c82d-11e9-86fe-4a5011f8bbf8.gif)

**Comment by gabro** [comment]
No, IIRC it doesn't. I suspect it's not terribly difficult to implement (/cc @olafurpg on this), but the more common scenario in which you want to import a specific type is supported.

**Comment by gabro** [comment]
This quickfix landed in master some weeks ago 🎉
