### ISSUE TITLE
The "New sbt workspace detected" prompt should default to "Import build"

### ISSUE THREAD

**Issue by bstaletic** [scalameta/metals-feature-requests#52]
**Is your feature request related to a problem? Please describe.**

Some clients don't support `showMessageRequest` and answering anything but "Import build" makes metals almost useless. The problem with `showMessageRequest` is that it is very intrusive - from the client perspective, `showMessageRequest` can happen at any time, interrupting whatever the user was doing.

**Describe the solution you'd like**

It would be very nice if metals treated "Method not found" error response as "Import build". While the `message` in the error response is arbitrary, the error code is always `-32601`.

**Describe alternatives you've considered**

Obviously, [ycmd](/ycm-core/ycmd) maintainers have considered implementing `showMessageRequest`, but there's a couple or reasons why that didn't happen yet:

- Except for metals, no other server needs `showMessageRequest` to work.
- We are still debating wether the intrusiveness of this request is worth it and if it is, what's the least intrusive way to implement the request.

**Additional context**

Right now, I'm testing metals with a simple patch that makes ycmd always respond to `showMessageRequest` with the first choice. This is clearly wrong, but it works for metals and, like I said, nothing else needs `showMessageRequest`.

**Search terms**:

**Comment by tgodzik** [comment]
Thanks for reporting! As a workaround you should be able to run `build import` manually.

I don't believe responding always with `import build` will be convenient in the long run. When editing `build.sbt` it could go a bit crazy. Maybe we could do it for the first request, when Metals is just being setup. However, I think running manual import command might be better. Opinions?

**Comment by bstaletic** [comment]
> As a workaround you should be able to run `build import` manually.

That's a reasonable workaround. How exactly do I run that? `build` isn't in my `$PATH`.

> I don't believe responding always with `import build` will be convenient in the long run. When editing `build.sbt` it could go a bit crazy.

That makes sense. You can probably tell, but I am not quite familiar with scala tooling - I'm just a LSP client maintainer.

> Maybe we could do it for the first request, when Metals is just being setup. However, I think running manual import command might be better. Opinions?

I wasn't aware of manual execution of `build import` being an option. If it's the first run and there's no data, it might still make sense to just go ahead and import the build.

**Comment by tgodzik** [comment]
> That's a reasonable workaround. How exactly do I run that? build isn't in my $PATH.

`build import` can be done via the `workspace/executeCommand` request `metals.build-import`

> That makes sense. You can probably tell, but I am not quite familiar with scala tooling - I'm just a LSP client maintainer.

We send messageRequest whenever the build definition changes (so the file changes) - same goes for gradle's `build.gradle` and maven's `pom.xml`.

> I wasn't aware of manual execution of build import being an option. If it's the first run and there's no data, it might still make sense to just go ahead and import the build.

I think it's a good option for anything not supporting MessageRequest.

**Comment by bstaletic** [comment]
> build import can be done via the workspace/executeCommand request metals.build-import

Then I must be doing something wrong.

Request:

```
2019-11-09 18:12:57,581 - DEBUG - TX: Sending message: b'Content-Length: 118\r\n\r\n{"id":2,"jsonrpc":"2.0","method":"workspace/executeCommand","params":{"arguments":[],"command":"metals.build-import"}}'
```
Response
```
2019-11-09 18:12:57,585 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":2,"result":{}}'
```

Nothing happened after that.

**Comment by bstaletic** [comment]
> Then I must be doing something wrong.

Figured it out. It should be `{"arguments":[],"command":"build-import"}`.

**Comment by olafurpg** [comment]
Thank you for reporting! The `workspace/showMessageRequest` is built into LSP and is necessary for Metals to support "import build" and "import build changes". I'm afraid that it's not a good idea to default those to the first choice since importing the build is a slow operation that can take multiple minutes to complete. It's important that users have the choice to decide when this happens, especially "import build changes".

As a workaround, users of ycmd can instead manually trigger the `build-import` command.
