### ISSUE TITLE
support Pants build system

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals-feature-requests#55]
We're using Pants as our build tool, so it would be great to see some support for it along with sbt, Maven, Gradle, Mill, etc.

https://www.pantsbuild.org/index.html

**Comment by gabro** [comment]
Hi @andyczerwonka, Pants support already landed on master a few weeks ago (see https://github.com/scalameta/metals/pull/935 for the initial PR) and it is still being refined before the next stable release.

If you're curious you can give it a try using the latest snapshot, but for "serious" use we recommend waiting for the stable release (which is likely to happen in January)
