### ISSUE TITLE
Support standalone Ammonite scripts

### ISSUE THREAD

**Issue by balhoff** [scalameta/metals-feature-requests#62]
I would like to edit a single [Ammonite](http://ammonite.io) `.sc` file that has its library [dependencies](http://ammonite.io/#IvyDependencies) defined within itself using `import $ivy…` etc., and see types and compiler errors. Ideally a separate project configuration wouldn't be required. I'm not sure which parts of this require Metals features vs. Ammonite features; I could open a separate issue with Ammonite if that is needed.

**Comment by balhoff** [comment]
There is already an issue for Ammonite that I think would relate to this: https://github.com/lihaoyi/Ammonite/issues/977

**Comment by tgodzik** [comment]
This is almost done via https://github.com/scalameta/metals-feature-requests/issues/80
