### ISSUE TITLE
Auto Implement methods of an interface or abstract class

### ISSUE THREAD

**Issue by mikail-khan** [scalameta/metals-feature-requests#67]
If a trait is defined as follows:

```scala
trait Foo {
   def bar(s : String) : Int
}
```
and a corresponding class which implements this trait as follows:

```scala
class Example() extends Foo{

}
```

It would be great to have a shortcut which inserted the `bar` method skeleton inside the class so the user just has to fill out the implementation, so

```scala
class Example() extends Foo{
   override def bar(s : String) : Int = ???
}
```

**Comment by gabro** [comment]
Hi! This is already a feature via completions.
Start typing the name of the method or "override" and you'll see it in the completion list

**Comment by co-category** [comment]
Hey @gabro 
Thanks for that. I didn't know that. However, I notice the follow:

If I just type `bar` I get two suggestions which end up producing this:

```scala

  bar()
  
  def bar(s: String): Int = ???

```

In the first case, the method signature is not fully generated and in the second case the override keyword doesn't get added.

If I start typing in override first, then it produces the correct and full method signature ie

```scala
override def bar(s: String): Int = ???
```

**Comment by gabro** [comment]
Can you provide a screenshot of the completion list you get?

**Comment by olafurpg** [comment]
@co-category thank you for reporting! The `override` keyword is optional so if your coding style requires it then you need to manually type "override def<COMPLETE>". It's expected that `bar()` is provided as a completion since it's valid to call that method (not override it).

**Comment by co-category** [comment]
@olafurpg @gabro I guess I am comparing it to Intellij. Intellij makes the intuitive completion by default i.e.

```scala
override def bar(s : String) : Int = ???
```

@gabro screenshots added

This is an unrelated problem: When having typed in a class identifier and I want to extend that class I don't get any a code completion suggestion for the keyword `extends` when that would be the most obvious one.

![p1](https://user-images.githubusercontent.com/13503259/72639327-4294a100-395d-11ea-82d9-0439fba980d8.png)

By starting to type `bar` and choosing the first option in the list of code completions I get the below. I would expect it to have at least put in the function arguments ie (s : String).

![p2](https://user-images.githubusercontent.com/13503259/72639428-7bcd1100-395d-11ea-8bb5-1e00579c9adf.png)


![p2-issue](https://user-images.githubusercontent.com/13503259/72639612-da928a80-395d-11ea-96e4-98682e42ad7f.png)

If I choose the second code completion option I get:

![p3](https://user-images.githubusercontent.com/13503259/72639630-eb430080-395d-11ea-8813-245bcd3ee292.png)

![p3-res](https://user-images.githubusercontent.com/13503259/72639637-f0a04b00-395d-11ea-9fcb-3e4d18f6d3eb.png)

**Comment by co-category** [comment]
Also say I have lots of abstract methods in the trait and I want to generate the code for each of them in the implementation class, Intellij has an option to do that. It shows a dialog box with all the methods and you can choose which ones you want. If you want all it will generate the skeletal code for each of them.

**Comment by co-category** [comment]
The latest release is really good though. My experience with using VS Code with Metals is getting better and smoother.

**Comment by olafurpg** [comment]
@co-category thank you for sharing your detailed feedback!

* The `extends` keyword is currently not supported in completions, you can subscribe to scalameta/metals#4420 to track that feature.
* Metals supports "implement all methods" since v0.8.0, see https://scalameta.org/metals/blog/2020/01/10/cobalt.html#completion-to-add-all-abstract-members This completion only comes up when extending a class with more than one abstract method.
* I would be open to discuss changing the ordering of `override def foo()` completions to that they appear above `foo()` method  calls.
* The `override` keyword will most likely continue to remain optional when extending abstract methods. If you strongly prefer to use `override`, then you can manually write the keyword. Metals tries to avoid configuration options by principle since it gets quickly difficult to maintain a project with 100s of options that can be combined in unexpected ways.

**Comment by gabro** [comment]
Thanks for the feedback @co-category!

To complement what @olafurpg said, there’s also this feature request to add also a code action (aka the lightbulb thingy in VS Code) for implementing abstract members stubs https://github.com/scalameta/metals-feature-requests/issues/59

The rationale of having both a completion and a code action is explained in the issue.

**Comment by mikail-khan** [comment]
> @co-category thank you for sharing your detailed feedback!
> 
> * The `extends` keyword is currently not supported in completions, you can subscribe to scalameta/metals#4420 to track that feature.
> * Metals supports "implement all methods" since v0.8.0, see https://scalameta.org/metals/blog/2020/01/10/cobalt.html#completion-to-add-all-abstract-members This completion only comes up when extending a class with more than one abstract method.
> * I would be open to discuss changing the ordering of `override def foo()` completions to that they appear above `foo()` method  calls.
> * The `override` keyword will most likely continue to remain optional when extending abstract methods. If you strongly prefer to use `override`, then you can manually write the keyword. Metals tries to avoid configuration options by principle since it gets quickly difficult to maintain a project with 100s of options that can be combined in unexpected ways.

Yeah I agree - that makes sense. You're following a different model, I just have to get used to it after years of using other IDEs. 👍 


> * I would be open to discuss changing the ordering of `override def foo()` completions to that they appear above `foo()` method  calls.

I would say that the completions needs to be more intelligent - if the class which has inherited the trait has not yet implemented the methods then make them appear at the top of the options.

**Comment by tanishiking** [comment]
FYI @mikail-khan  https://github.com/scalameta/metals/pull/1379 added Code Action to implement non-implemented abstract members. Perhaps, does this satisfies your feature request?

**Comment by gabro** [comment]
Good call @tanishiking. I think this feature request can be closed. We’ve discussed a few things in this issue, so if there’s anything left that is still missing I think it’s best to open a new, more focused, feature request
