### ISSUE TITLE
Export worksheet output

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-feature-requests#74]
**Is your feature request related to a problem? Please describe.**

Currently, when using worksheets I take screenshots of VS Code when I need to share the output of the worksheet. For example

<img width="477" alt="Screenshot 2020-02-02 at 10 11 57" src="https://user-images.githubusercontent.com/1408093/73606816-16f0f800-45a6-11ea-985c-c6604d66840f.png">

**Describe the solution you'd like**

It would be nice if I should share worksheets in a textual format. For example, "Copy worksheet output to clipboard" or something like that.

**Describe alternatives you've considered**

Taking screenshots of VS Code.

**Additional context**

Idea from @tgodzik , we could reuse the worksheet printer for editors like sublime that don't support non-decorations to render the output in a textual format somehow. 

It would be nice to include the hover message as well.

**Search terms**:

Worksheets, share, export clipboard, copy-paste

**Comment by tgodzik** [comment]
This was actually done in https://github.com/scalameta/metals/pull/2290 :tada:

**Comment by pabloagn** [comment]
Hey guys, following up on this implementation, is it possible to copy just a given expression output to the clipboard, instead of the whole workbook?

**Comment by tgodzik** [comment]
> Hey guys, following up on this implementation, is it possible to copy just a given expression output to the clipboard, instead of the whole workbook?

Not currently, we could try using inlay hints at some point, which might be helpful here, since it allows for a command to be invoked.

**Comment by pabloagn** [comment]
Got it, thanks for the update
