### ISSUE TITLE
Use git mv when renaming files if git is available

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals-feature-requests#75]
**Is your feature request related to a problem? Please describe.**

When you rename/move a file in VS Code, it uses the `git mv` command (I assume: if git is available and the workspace has git enabled), which reduces diffs.

The current rename implementation just renames the file, somehow circumventing the editor's behavior. It would be nice if it didn't do that.

**Describe the solution you'd like**
Renaming programatically has the same effect as renaming in the editor.

**Describe alternatives you've considered**
Manually moving the file back and forth.

**Search terms**:
git, move, mv, rename, diff

**Comment by tgodzik** [comment]
Thanks for reporting! I checked to make sure and it's actually VS Code that's doing it. We just send a request for rename:

https://github.com/scalameta/metals/blob/1c23e3f9bf757cf27974975c6012fff004e60083/metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala#L188

**Comment by kubukoz** [comment]
Hold on, I'll need to check if it's actually VS Code or GitLens...

**Comment by kubukoz** [comment]
Interesting, I tried with GitLens off and on, and it looks like the editor isn't actually using the command. I was under the impression it did, because I had small diffs when moving files myself, but not recently, when I renamed a symbol with Metals... I think we can close this then. Sorry :)
