### ISSUE TITLE
Skip parenthesis when completing `()`-ary method

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals-feature-requests#76]
**Is your feature request related to a problem? Please describe.**
Completing a method like `"".toUpper<cursor>Case()` shouldn't always insert the parenthesis.

**Describe the solution you'd like**

A way to skip `()`.

Possibly as:
- a flag in language server options (as some users will likely want to keep the behavior), or
- a project- or globally-scoped list of symbols that should or shouldn't have a pair of parens inserted. For example, `java.lang.String#toUpperCase()` would be fine without parens, but `java.util.List#clear` would be frowned upon.

**Describe alternatives you've considered**
Manually removing the parens.

**Search terms**:
parenthesis, parens, complete, nullary, arguments, function, method

**Comment by gabro** [comment]
I personally think it's not a good idea to make this configurable. Here's a couple reasons why:

1. About the specific case, as far as I remember (I can't find the discussion anymore) Scala 3 is going towards the direction of making this more regular so that:

    - methods without parameter lists cannot be invoked with parenthesis
    - methods with an empty parameter list must be invoked with parenthesis

    About Java methods specifically there may be some leeway (e.g. they're allowed to be called without parenthesis).

    Metals currently follows a very similar convention:

    - do not add `()` for methods defined without a parameter list
    - add `()` for methods defined with an empty parameter list, including Java ones.

    I personally value consistency over ad-hoc aesthetic choices, so I like that Metals applies a consistent standard (it can be the opposite of the current default, I don't have a strong opinion about it). I've started using `()` for Java methods since I switched to Metals, and I don't really mind, since I don't have to type them :P


2. More in general, configuration options may seem "innocent" when considered in isolation, but they quickly explode in complexity and it becomes hard to test all the possible combinations. Scalafmt (and a stray of its reported bugs) is a good example of what happens when configuration options explode (even with the noble intent of pleasing all users).

    Metals has always followed the philosophy of avoiding user-facing configuration options unless absolutely necessary and I think this has paid off well so far.

    With this in mind, I don't think this specific use case holds its weight for a configuration option.

**Comment by kubukoz** [comment]
I agree, consistency is probably a sane default and the behavior is consistent with Scala 3 :) thanks for the feedback.

**Comment by kubukoz** [comment]
btw. @gabro do you think it's worth mentioning the principle of avoiding configuration in the contributing guide?

**Comment by gabro** [comment]
I think it is, and @olafurpg and I discussed this a few times in the past, but never found the focus to put this into a document.

I've always the format of https://github.com/concourse/concourse/wiki/Anti-Patterns, in case someone wants to take this on and they're looking for inspiration.
