### ISSUE TITLE
`adt` / `enum` completion

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals-feature-requests#79]
**Is your feature request related to a problem? Please describe.**

There's a relatively large amount of boilerplate in ADT / dotty-like-enum definitions in Scala 2. Let's take something similar to `Option`, for example:

```scala
sealed trait Option[A] extends Product with Serializable
object Option {
  final case class Some[A](get: A) extends Option[A]
  case object None extends Option[Nothing]

  //extra: smart constructors (could be another completion)
  def some[A](a: A): Option[A] = Some(a)
  def none[A]: Option[A] = None
}
```

Let's ignore variance for this issue.

Here are the tokens relevant for the user, in order of typing:

```scala
Option, A, Some, get: A, None, Nothing
```

Everything else is noise that could be generated.

I'm not sure to what extent this is achievable with completion snippets (i.e. if it's possible to add new members of the type after you're done typing all the details of previous members, but it would be nice to have.

**Describe the solution you'd like**

Some sort of completion, e.g. `Option[A].enum<tab>` that expands to

```scala
sealed trait Option[A] extends Product with Serializable
object Option {
  {$1} extends Option[{$2}]

  def {$1.lowercase}[/*this would appear if $1 had any type parameters*/{$3}](a: A): Option[{$3}] = $1(args)
}
```

**Describe alternatives you've considered**

Manually writing ADTs, using custom external codegen tools.

**Additional context**
Dotty's enums solve the problem of boilerplate.

**Search terms**:
enum, adt, boilerplate, product, serializable, gadt

**Comment by gabro** [comment]
I think this is a perfect example for a snippet. Metals should be able to provide one via completions for editors that support snippets

**Comment by kubukoz** [comment]
tbh I don't think this is *that* valuable anymore, the boilerplate is tedious but the amount of effort to implement anything more than simple snippets (which everyone can define in their IDE in a matter of minutes) would be an even greater waste of time. Especially with Dotty around the corner.
