### ISSUE TITLE
Add keybindings for Run and Debug

### ISSUE THREAD

**Issue by robbyki** [scalameta/metals-feature-requests#81]
**Is your feature request related to a problem? Please describe.**
Currently can only initiate the `run | debug` commands using the links that get created directly above the application. A bit of a pain to always have to scroll up and use the mouse to launch run or debug. 

**Describe the solution you'd like**
It would be great to be able to add keybindings to the feature. 

**Search terms**:
keyboard run debug keybinding

**Comment by tgodzik** [comment]
Thanks for reporting, I think this is closely related to https://github.com/scalameta/metals-feature-requests/issues/72 but not necessarily the same. I think this would be super useful to have.

**Comment by tgodzik** [comment]
You should be able to run the current file using F5 in Vs Code currently (if no launch json is specified, but it can also be invoked manually), it will make you choose a main class if there is more than one. I think that's the best experience we can offer here. One improvement would be to also try to figure out which code lense are closer to the code lense, but I think choosing the main class to run is rather a small price.

**Comment by tgodzik** [comment]
Also, you can invoke a command `Run main class or tests in the current file` in VS Code starting with https://github.com/scalameta/metals-vscode/pull/860 that should work perfectly well for the use case. This can be bound to a shortcut and used in other editors also.
