### ISSUE TITLE
Debug Support for Emacs using dap-mode. Is it possible?

### ISSUE THREAD

**Issue by CsBigDataHub** [scalameta/metals-feature-requests#84]
Checking if debugging for scala metals can be implemented in emacs with dap-mode.
https://github.com/emacs-lsp/dap-mode

**Comment by ckipp01** [comment]
Hey @CsBigDataHub thanks for the request! It looks like the [`lsp-mode metals client settings`](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-metals.el) already has `dap-mode` enabled for Metals! You should be able to already use `dap-mode` via `lsp-mode`.

**Comment by CsBigDataHub** [comment]
Thanks @ckipp01 . Probably this table needs to be updated for emacs at 'run/debug' row.
https://scalameta.org/metals/docs/editors/overview.html
